/* Created by Administrator on 2016/1/6.*/
/* Update by ligen at 2016/2/26.*/
/*========================参数说明========================*/
/* wendaoMoney   问道币模版字符串                         */
/* role          角色模版字符串                           */
/* daoju         道具模版字符串                           */
/* pet           宠物模版字符串                           */
/* equip         装备模版字符串                           */
/* equipOther    装备(指的是法宝 首饰 娃娃部分)模版字符串 */
/* roleview      角色详情模版字符串                       */
/* bag           背包详情模版字符串                       */
/*========================================================*/
(function (window) {
    //模版字符串对象
    var templateString = {};
    //道具部分的html模版
    //存放在数组中通过join方法拼接
    //其中（@ @）两个@之间的 是需要替换的 其他部分和html无异
    //问道币模版字符串
    templateString.wendaoMoney = ['<div class="templateString-border" id="templateString_wendaoMoney">',
         '            <div class="imgleft iehkil">',
         '                 <img src="http://img.gyyxcdn.cn/qibao/Images/itemImages/wdb.jpg" width="50">',
         '             </div>',
         '             <div class="imgright textcenter">',
         '                  <span  style="color:#ffff00">问道币</span><br>',
         '                  <span class="moneyNum" style="color:@moneyColor@;white-space: nowrap">@moneyNum@</span>',
         '              </div>',
         '    </div>'].join("");
    //角色模版字符串
    templateString.role = ['<div class="templateString-border" id="templateString_role">',
          '            <div class="imgleft" style="margin-top:-25px;">',
          '                  <img src="http://img.gyyxcdn.cn/qibao/Images/itemImages/@icon@.jpg" width="50">',
          '            </div>',
          '            <div>',
          '                  <div class="name">角色名称：@name@</div>',
          '                  <div class="party_name">角色门派：@polar@</div>',
          '                  <div class="level" style="display:flex">角色等级：@level@</div>',
          '                  <div class="tao">角色道行：@tao@</div>',
          '                  <span class="con" style="white-space: nowrap;margin-right: 20px;">体质：@con@</span>',
          '                  <span class="wiz" style="white-space: nowrap;">灵力：@wiz@</span><br/>',
          '                  <span class="str" style="white-space: nowrap;margin-right: 20px;">力量：@str@</span>',
          '                  <span class="dex" style="white-space: nowrap">敏捷：@dex@</span>',
          '             </div>',
          '    </div>'].join("");
    //道具模版字符串
    templateString.daoju = ['<div class="templateString-border" id="templateString_daoju">',
          '            <div class="imgleft" style="_margin-left:150px; _display:block;">',
          '                @important_item@<img src="http://img.gyyxcdn.cn/qibao/Images/bigdaojuImages/@icon@.jpg" width="120">',
          '            </div>',
          '            <div>',
          '                  <div class="name" style="color:@color@;white-space: nowrap">@name@</div>',
          '                  <div class="source">@prop_desc@</div>',
          //'                  <div class="skill_description clearfix" style="width: 160px;">技能描述：@inborn_stone_attrib_pve@@inborn_stone_attrib_pvp@</div>',
          '                  <div class="min_req_level clearfix">@min_req_level@</div>',
      '            <div class="yld_capacity_level" style="color:@color@; ">@yld_capacity_level@</div>',
          '                  <div class="change_pet_name" style="color:@color@; ">@change_pet_name@</div>',
          '                  <div class="default_capacity_level" style="color:@color@; ">@default_capacity_level@</div>',
          '                  <div class="qihun_intimacy" style="color:@color@; ">@qihun_intimacy@</div>',
          '                  <div class="level clearfix">等级：@level@</div>',
          '                  <div class="nimbus clearfix">灵气：@nimbus@</div>',
          '                  <div class="req_level clearfix">携带等级：@req_level@</div>',
          '                  <div class="basic_attrib  clearfix">@basic_attrib@</div>',
          '                  <div class="upgrade_type  clearfix">类型：@upgrade_type@</div>',
          '                  <div class="exp clearfix">经验：@exp@/@exp_to_next_level@</div>',
          '                  <div class="durability clearfix">耐久度：@durability@/@max_durability@</div>',
          '                  <div class="item_polar clearfix" style="color: #00ff00">相性：@item_polar@</div>',
          '                   <div class="str clearfix">@str@</div>',
          '                   <div class="con clearfix">@con@</div>',
          '                   <div class="wiz clearfix">@wiz@</div>',
          '                   <div class="dex clearfix">@dex@</div>',
          '                  <div class="lingyun_cumulate clearfix">灵蕴升阶完成度：@lingyun_cumulate@</div>',
          '                   <div class="standard_properties clearfix">@standard_properties@</div>',
          '                   <div class="protect_standard_properties clearfix">@protect_standard_properties@</div>',
          '                   <div class="incarnation_intimacy clearfix"><span style="color:@color@">当前友好度：</span>@incarnation_intimacy@</div>',
          '                   <div class="incarnation_intimacy_cumulate clearfix"><span style="color:@color@">交情：</span>@incarnation_intimacy_cumulate@</div>',
          '                  <div class="attrib">@attrib@</div>',
          '                  <div><span class="extra_skill" style="color:@color@; ">特殊技能：@extra_skill@</span><span class="extra_skill_level" style="color:@color@; ">(@extra_skill_level@级)</span></div>',
          '                  <div><span class="seal_name" style="color: #9090ff">守护兽：@seal_name@</span><span class="seal_sealrank_desc"  style="color: #9090ff">(@seal_sealrank_desc@)</span></div>',
          '                  <div><span class="seal_level" style="color: #9090ff;margin-right: 20px;">等级：@seal_level@</span>',
          '                  <span class="seal_polar" style="color: #00ff00">相性：@seal_polar@</span></div>',
          '                  <div class="seal_attrib" style="color: #00FFFF">@seal_attrib@</div>',
          '                  <div class="min_equip_lv">@min_equip_lv@@transformOrder@</div>',
          '                  <div class="no_min_equip_lv">@no_min_equip_lv@</div>',
          '                 <div class="suoln_text_desc">@suoln_text_desc@</div>',
           '                 <div class="suoln_rank_desc">@suoln_rank_desc@</div>',
          '                 <span class="suoln_extra_min">@suoln_extra_min@</span>',
          '                 <span class="suoln_extra_max">@suoln_extra_max@</span>',
           '                 <div class="suoln_extra_avg">@suoln_extra_avg@</div>', 
           '                <div class="niantou_desc">@niantou_desc@</div>',

          '             </div>',
          '        </div>'].join("");
    //宠物模版字符串
    templateString.pet = ['<div class="templateString-border" id="templateString_pet">',
        '                <div class="clearfix" style="padding-bottom: 10px;+width: 520px;width: 550px;">',
        '                        <div class="left" style="width: 130px;margin-right:20px;height:130px;float: left;">',
        '                                <img src="http://img.gyyxcdn.cn/qibao/Images/bigItemImages/@icon@.jpg" width="130" height="130" style="border: none">@property_bind_attrib@',
        '                            </div>',
        '                        <div class="right" style="float: left">',
        '                                <div class="name" style="width: 330px;text-align:center;color:#11ff11">@name@@rank@<span class="polar">@polar@</span></div>',
        '                                <div class="templateString_pet_attr_up">',
        '                                        <dl class="level">',
        '                                                <dt>等级：</dt>',
        '                                                <dd>@level@</dd>',
        '                                            </dl>',
        '                                        <dl class="phy_power">',
        '                                                <dt>物伤：</dt>',
        '                                                <dd>@phy_power@</dd>',
        '                                            </dl>',
        '                                        <dl class="req_level">',
        '                                                <dt>携带等级：</dt>',
        '                                                <dd>@req_level@</dd>',
        '                                            </dl>',
        '                                        <dl class="mag_power">',
        '                                                <dt>法伤：</dt>',
        '                                                <dd>@mag_power@</dd>',
        '                                            </dl>',
        '                                        <dl class="retain_intimacy">',
        '                                                <dt>亲密度：</dt>',
        '                                                <dd>@retain_intimacy@</dd>',
        '                                            </dl>',
        '                                        <dl class="speed">',
        '                                                <dt>速度：</dt>',
        '                                                <dd>@speed@</dd>',
        '                                            </dl>',
        '                                        <dl class="life">',
        '                                                <dt>气血：</dt>',
        '                                                <dd>@life@/@max_life@</dd>',
        '                                            </dl>',
        '                                        <dl class="def">',
        '                                                <dt>防御：</dt>',
        '                                                <dd>@def@</dd>',
        '                                            </dl>',
        '                                        <dl class="mana">',
        '                                                <dt>法力：</dt>',
        '                                                <dd>@mana@/@max_mana@</dd>',
        '                                            </dl>',
        '                                        <dl class="martial">',
        '                                                <dt>武学：</dt>',
        '                                                <dd>@martial@</dd>',
        '                                            </dl>',
        '                                        <dl class="martial pet_classicHidden">',
        '                                                <dt>战力：</dt>',
        '                                                <dd>@zhanli_score@</dd>',
        '                                            </dl>',
        '                                        <div class="templateStringAttriPic pet_classicHidden">',
        '                                           <dl class="pet_polar">',                 
        '                                             <dd>@pet_polar@</dd>',
        '                                        </dl>',
        '                                         <dl class="pet_mounttype">',                 
        '                                             <dd>@pet_mounttype@</dd>',
        '                                        </dl>',
        '                                         <dl class="pet_rebirth">',                 
        '                                             <dd>@pet_rebirth@</dd>',
        '                                        </dl>',
        '                                         <dl class="pet_qianghua">',                 
        '                                             <dd>@pet_qianghua@</dd>',
        '                                        </dl>',
        '                                         <dl class="pet_enchant">',                 
        '                                             <dd>@pet_enchant@</dd>',
        '                                        </dl>',
        '                                         <dl class="pet_eclosion">',                 
        '                                             <dd>@pet_eclosion@</dd>',
        '                                        </dl>',     
        '                                         <dl class="pet_huanhua">',                 
        '                                             <dd>@pet_huanhua@</dd>',
        '                                        </dl>',
        '                                         <dl class="pet_primarypro">',                 
        '                                             <dd>@pet_primarypro@</dd>',
        '                                        </dl>',
        '                                         <dl class="label_pic">',
        '                                                <dd>@cwspan@</dd>',
        '                                        </dl>',
        '                                         <dl class="label_pic">',
        '                                                <dd>@pet_tongyuan_tp@</dd>',
        '                                        </dl>',
        '                                       <span>@avatarIcon@</span>',
        '</div>',
        '                                    </div>',
        '                            </div>',
        '                    </div>',
        '                <div class="templateString_pet_attr_down templateString-color-green clearfix" style="width: 550px">',
        '                    <dl class="default_capacity_level" style="width: 100%;color: #ff6600;">',
        '                        <dt>能力阶位：</dt>',
        '                        <dd>@default_capacity_level@</dd>',
        '                    </dl>',
        '                    <dl class="shape  templateString-color-blue" style="width: 100%;">',
        '                        <dt>成　　长：</dt>',
        '                        <dd>@shape@</dd>',
        '                    </dl>',
        '                    <div style=""  class="clearfix">',
        '                        <dl class="pet_life_shape">',
        '                            <dt class="">血量成长：</dt>',
        '                            <dd>@pet_life_shape@</dd>',
        '                        </dl>',
        '                        <dl class="pet_mana_shape">',
        '                            <dt class="">法力成长：</dt>',
        '                            <dd>@pet_mana_shape@</dd>',
        '                        </dl>',
        '                        <dl class="pet_phy_shape">',
        '                            <dt class="">物攻成长：</dt>',
        '                            <dd>@pet_phy_shape@</dd>',
        '                        </dl>',
        '                        <dl class="pet_mag_shape">',
        '                            <dt class="">法攻成长：</dt>',
        '                            <dd>@pet_mag_shape@</dd>',
        '                        </dl>',
        '                        <dl class="pet_speed_shape">',
        '                            <dt class="">速度成长：</dt>',
        '                            <dd>@pet_speed_shape@</dd>',
        '                        </dl>',
        '                    </div>',
        '                    <dl class="morph" style="width: 100%;">',
        '                        <dt class="templateString-color-blue">幻　　化：</dt>',
        '                        <dd>@morph@</dd>',
        '                    </dl>',
        '                    <dl class="illusion" style="width: 100%;color: #ff6600;">', //illusion:表示幻化
        '                        <dt>@illusion_name@</dt>',
        '                        <dd>@morph_life_times@@morph_mana_times@@morph_mag_times@@morph_phy_times@@morph_speed_times@@dongjie@</dd>',
        '                    </dl>',
        '                    <dl class="strengthen" style="width: 100%;color: #ff6600;">', //strengthen:表示强化
        '                        <dt>强　　化：</dt>',
        '                        <dd><span class="phy_rebuild_level">物攻@phy_rebuild_level@次</span><span class="mag_rebuild_level">法攻@mag_rebuild_level@次</span></dd>',
        '                    </dl>',
        '                    <dl class="innateskills" style="width: 100%;">',
        '                        <dt class="templateString-color-blue">天生技能：</dt>',
        '                        <dd>@innateskills@</dd>',
        '                    </dl>',
        '                    <dl class="talentskills" style="width: 100%;">',
        '                        <dt class="templateString-color-blue">天赋技能：</dt>',
        '                        <dd style="color: #ffffff">@talentskills@</dd>',
        '                    </dl>',
        '                    <dl class="hunshoustone" style="width: 100%;">',
        '                        <dt class="templateString-color-blue">魂兽石　：</dt>',
        '                        <dd style="color: #ffffff">@hunshoustone@</dd>',
        '                    </dl>',
        '                    <dl class="reincarnationskills" style="width: 100%;">',
        '                        <dt class="templateString-color-blue">轮回技能：</dt>',
        '                        <dd>@reincarnationskills@</dd>',
        '                    </dl>',
        '                    <dl class="epiphanyskills" style="width: 100%;">',
        '                        <dt class="templateString-color-blue">顿悟技能：</dt>',
        '                        <dd>@epiphanyskills@</dd>',
        '                    </dl>',
        '                    <dl class="ghostpetskills" style="width: 100%;">',
        '                        <dt class="templateString-color-blue">鬼宠技能：</dt>',
        '                        <dd>@ghostpetskills@</dd>',
        '                    </dl>',
/*        '                    <dl class="teachingskills" style="width: 100%;">',
        '                        <dt class="templateString-color-blue">师门技能：</dt>',
        '                        <dd>@teachingskills@</dd>',
        '                    </dl>',
        '                    <dl class="mumbojumboskills" style="width: 100%;">',
        '                        <dt class="templateString-color-blue">天书技能：</dt>',
        '                        <dd>@mumbojumboskills@</dd>',
        '                    </dl>',*/
        '                    <dl class="heartskills" style="width: 100%;">',
        '                        <dt class="templateString-color-blue">心　　法：</dt>',
        '                        <dd>@heartskills@</dd>',
        '                    </dl>',
        '                    <dl class="epiphanyskills" style="width: 100%;">',
        '                        <dt class="templateString-color-blue">神通技能：</dt>',
        '                        <dd>@avatarskills@</dd>',
        '                    </dl>',
        '                    <dl class="attrib_point templateString-color-blue" style="width: 100%;">',
        '                        <dt class="">属　　性：</dt>',
        '                        <dd>剩余属性点数(@attrib_point@)</dd>',
        '                    </dl>',
        '                    <div style=""  class="templateString-color-green">',
        '                        <span class="con">体质 @con@</span>',
        '                        <span class="wiz">灵力 @wiz@</span>',
        '                        <span class="str">力量 @str@</span>',
        '                        <span class="dex">敏捷 @dex@</span>',
        '                    </div>',
        '                    <dl class="resist_point templateString-color-blue" style="width: 100%;">',
        '                        <dt class="">抗　　性：</dt>',
        '                        <dd>剩余抗性点数(@resist_point@)</dd>',
        '                    </dl>',
        '                    <div style=""  class="templateString-color-green">',
        '                        <span class="resist_earth">抗土  @resist_earth@</span>',
        '                        <span class="resist_metal">抗金  @resist_metal@</span>',
        '                        <span class="resist_wood">抗木  @resist_wood@</span>',
        '                        <span class="resist_water">抗水  @resist_water@</span>',
        '                        <span class="resist_fire">抗火  @resist_fire@</span>',
        '                        <span class="resist_poison">抗中毒 @resist_poison@</span>',
        '                        <span class="resist_sleep">抗昏睡 @resist_sleep@</span>',
        '                        <span class="resist_confusion">抗混乱 @resist_confusion@</span>',
        '                        <span class="resist_repress">抗镇魂 @resist_repress@</span>',
        '                        <span class="resist_cage">抗水牢 @resist_cage@</span>',
        '                        <span class="resist_lock">抗锁灵 @resist_lock@</span>',
        '                        <span class="resist_lost">抗迷心 @resist_lost@</span>',
        '                        <span class="resist_forgotten">抗遗忘 @resist_forgotten@</span>',
        '                        <span class="resist_frozen">抗冰冻 @resist_frozen@</span>',
        '                        <span class="resist_melt">抗化功 @resist_melt@</span>',
        '                    </div>',
        '                    <dl class="dunwu_total_times templateString-color-blue" style="width: 100%;">',
        '                        <dt>顿　　悟：</dt>',
        '                        <dd>@dunwu_left_times@ @dunwu_total_times@</dd>',
        '                    </dl>',
        '                    <dl class="medicine_used" style="width: 100%;">',
        '                        <dt class="templateString-color-blue">服　　用：</dt>',
        '                        <dd>@medicine_used@</dd>',
        '                    </dl>',
        '                    <dl class="extra_attrib" style="width: 100%;">',
        '                        <dt class="demonstone templateString-color-blue">妖　　石：</dt>',
        '                        <dd>@extra_attrib@</dd>',
        '                    </dl>',
        '                    <div style=""  class="templateString-color-green">',
        '                    </div>',
        '                    <dl class="evolve" style="width: 100%;">',
        '                        <dt class="templateString-color-blue">魂　　魄：</dt>',
        '                        <dd>@evolve@</dd>',
        '                    </dl>',
        //'                    <dl class="merge_rate" style="width: 100%;">',
        //'                        <dt class="templateString-color-blue">融合完成度：</dt>',
        //'                        <dd>@merge_rate@</dd>',
        //'                    </dl>',
        '                    <dl class="pet_godbooks templateString-color-blue">',
        '                        <dt>天书技能：</dt>',
        '                        <dd>@pet_godbooks@</dd>',
        '                    </dl>',
        '                    <dl class="dunwu_left_times templateString-color-blue" style="width: 100%;">',
        '                        <dt>本　　尊：</dt>',
        '                        <dd><span class="templateString-color-green">@raw_name@</span></dd>',
        '                    </dl>',
        '                    <p class="merge_rate templateString-color-blue"></p>',
        //'                    <p class="property_bind_attrib">属性绑定：@property_bind_attrib@</p>',
        '                    <p class="recognize_recognized">认主绑定：@recognize_recognized@</p>',
        '                    <p class="enchant templateString-color-blue">@enchant@</p>',
        '                    <p class="important_item templateString-color-blue">@important_item@</p>',
        '                    <p class="zhanli_lv templateString-color-blue">@zhanli_lv@</p>',
        '                    <p class="eclosion templateString-color-blue">@eclosion@</p>',
        '                    <p class="merge_rate templateString-color-blue" style="color: #ff6600;">@merge_rate@</p>',
        '                    <p class="seal templateString-color-blue">@seal@</p>',
        '                    <p class="templateString-color-white">@property_left_time@</p>',
        '                    <dl class="templateString-color-blue pet_classicHidden" style="width: 100%;">',
        '                        <dt>相　　性：</dt>',
        '                        <dd>@pet_polartit@</br>@pet_polarcont@</dd>',
        '                    </dl>',
        '                    <dl class="tongyuan templateString-color-blue pet_classicHidden" style="width: 100%;">',
        '                        <dt>同　　源：</dt>',
        '                        <dd>@tongyuan_label@</br>@pet_tongyuan@</dd>',
        '                    </dl>',
        '                    <dl class="pet_nature_yang templateString-color-blue" style="width: 50%;">',
        '                        <dt>阳天性点：</dt>',
        '                        <dd>@pet_nature_yang@</dd>',
        '                    </dl>',
         '                    <dl class="pet_nature_yin templateString-color-blue" style="width: 50%;">',
        '                        <dt>阴天性点：</dt>',
        '                        <dd>@pet_nature_yin@</dd>',
        '                    </dl>',
        '                    <dl class="tongyuan templateString-color-blue pet_classicHidden" style="width: 100%;">',
        '                        <dt>同源突破：</dt>',
        '                        <dd>@pet_ty_basic@</dd>',
        '                    </dl>',
        '                    <dl class="tongyuan templateString-color-blue pet_classicHidden" style="width: 100%;">',
        '                        <dt>　参　战：</dt>',
        '                        <dd>@pet_ty_cz@</dd>',
        '                    </dl>',
        '                    <dl class="tongyuan templateString-color-blue pet_classicHidden" style="width: 100%;">',
        '                        <dt style="color:#ff00ff">　掠　阵：</dt>',
        '                        <dd>@pet_ty_lz@</dd>',
        '                    </dl>',
        '                    <dl class=" templateString-color-blue" style="width: 100%;">',
        '                        <dt>@pet_lingpo_basic@</dt>',
        '                        <dd>@pet_lingpo@</dd>',
        '                    </dl>',
        '                    <dl class="templateString-color-blue" style="width: 100%;">',
        '                        <dt>血　　脉：</dt>',
        '                        <dd>@pet_blood@</dd>',
        '                    </dl>',
        

        '</div>',
    ].join("");
    //装备模版字符串
    templateString.equip = ['<div class="templateString-border clearfix" id="templateString_equip">',
        '        <div class="imgleft" style="_margin-left:150px;">',
        '            @important_item@<img src="http://img.gyyxcdn.cn/qibao/Images/bigdaojuImages/@icon@.jpg" width="120" style="width:120px;">@property_bind_attrib@',
        '        </div>',
        '        <div class="textcenter">',
        '            <div class="name">@seal_icon@@name@@suit_polar@@rebuild_level@</div>',
        '            <div class="evolvelevel" style="color:#ff2020">@req_level@</div>',
        '            <div class="isevolvelevel">@isevolvelevel@</div>',
        '            <div class="source" style="color: #ff2020">@source@</div>',
        '            <div class="holes" style="line-height: 0px;">',
        '                <img src="http://img.gyyxcdn.cn/qibao/Images/FlashImages/@hole1@.png" alt=""/ style="width:16px;">',
        '                <img src="http://img.gyyxcdn.cn/qibao/Images/FlashImages/@hole2@.png" alt=""/ style="width:16px;">',
        '                <img src="http://img.gyyxcdn.cn/qibao/Images/FlashImages/@hole3@.png" alt=""/ style="width:16px;">',
        '            </div>',
        '            <div class="shuxxls_times" style="color:#ff2020">@shuxxls_times@</div>',
        '            <div class="basic_limit">@basic_limit@</div>',
        '            <div class="basic_attrib">@basic_attrib@</div>',
        '            <div class="fairy_class">@fairy_class@@fairy_layer@@fairy_attribs@</div>',
        '            <div class="attrib">@attrib@</div>',
        '            <div class="attrib">@seal_pet_name@</div>',
        '            <div class="attrib">@property_left_time@</div>',
        '            <div class="limit_exchange_left_time">@limit_exchange_left_time@</div>',
        '        </div>',
        '</div>'].join("");
    //装备(指的是法宝 首饰 娃娃部分)模版字符串
    templateString.equipOther = ['<div>',
        '    <div class="templateString-border" id="templateString_daojuother">',
        '            <div class="imgleft" style="_margin-left:150px;">',
        '                @important_item@<img src="http://img.gyyxcdn.cn/qibao/Images/bigdaojuImages/@icon@.jpg" width="120">@property_bind_attrib@',
        '            </div>',
        '            <div class="textcenter">',
        '                  <div class="name" style="color:@color@;white-space: nowrap">@name@</div>',
        '                  <div class="source">出品人：@source@</div>',
        '                  <div class="skill_description clearfix" style="width: 160px;">技能描述：@inborn_stone_attrib_pve@@inborn_stone_attrib_pvp@</div>',
        '                  <div class="level clearfix">等级：@level@</div>',
        '                  <div class="req_level clearfix">等级需求：@req_level@</div>',
        '                  <div class="nimbus clearfix">灵气：@nimbus@</div>',
        '                  <div class="basic_attrib  clearfix">@basic_attrib@</div>',
        '                  <div class="exp clearfix">道法：@exp@/@exp_to_next_level@</div>',
        '                  <div class="item_polar clearfix">相性：@item_polar@</div>',
        '                  <div class="item_polar_bm clearfix">相性：@item_polar_bm@</div>',
        '                  <div class="retain_intimacy  clearfix">亲密度：@retain_intimacy@</div>',//增加法宝亲密度
        '                  <div class="fairy_class clearfix">@fairy_class@</div> ',//增加境界
        '                  <div class="attrib">@attrib@</div>',
        '                  <div class="child_phy_stunt">@child_phy_stunt@</div>',
        '                  <div class="child_mag_stunt">@child_mag_stunt@</div>',
        '                  <div class="child_ir_water">@child_ir_water@</div>',
        '                  <div class="child_ir_earth">@child_ir_earth@</div>',
        '                  <div class="child_ir_wood">@child_ir_wood@</div>',
        '                  <div class="child_ir_fire">@child_ir_fire@</div>',
        '                  <div class="child_ir_metal">@child_ir_metal@</div>',
        '                  <div class="child_rd_water">@child_rd_water@</div>',
        '                  <div class="child_rd_earth">@child_rd_earth@</div>',
        '                  <div class="child_rd_wood">@child_rd_wood@</div>',
        '                  <div class="child_rd_fire">@child_rd_fire@</div>',
        '                  <div class="child_rd_metal">@child_rd_metal@</div>',
        '                  <div class="child_reduce_mag">@child_reduce_mag@</div>',
        '                  <div class="child_reduce_phy">@child_reduce_phy@</div>',
        '                  <div class="child_damage_reduce">@child_damage_reduce@</div>',
        '                  <div class="child_physique">@child_physique@</div>',
        '                  <div class="child_str">@child_str@</div>',
        '                  <div class="child_wisdom">@child_wisdom@</div>',
        '                  <div class="child_dex">@child_dex@</div>',
        '                  <div class="child_rr_anger">@child_rr_anger@</div>',
        '                  <div class="child_ig_anger">@child_ig_anger@</div>',
        '                  <div class="child_ignore_def">@child_ignore_def@</div>',
        '                  <div class="phy_effect">@phy_effect@</div>',
        '                  <div class="mag_effect">@mag_effect@</div>',
        '                  <div class="stun_impr">@stun_impr@</div>',
        '                  <div class="durability clearfix">耐久度：@durability@/@max_durability@</div>',
        '                  <div class="attach_skill_bm">@attach_skill_bm@</div>',
        '                  <div><span class="trigger_rate"">@trigger_rate@</span></div>',
        '                  <div><span class="trigger_rate_bm"">副技能：@trigger_rate_bm@</span></div>',
        '                  <div><span class="extra_skill" style="color:@color@; ">特殊技能：@extra_skill@</span><span class="extra_skill_level" style="color:@color@; ">(@extra_skill_level@级)</span><span class="extra_skill_bm" style="color:@color@; ">&nbsp;&nbsp;@extra_skill_bm@</span><span class="extra_skill_level_bm" style="color:@color@; ">(@extra_skill_level_bm@级)</span></div>',
        '                  <div><span class="seal_name" style="color: #9090ff">守护兽：@seal_name@</span><span class="seal_rank_desc" style="color: #9090ff">(@seal_rank_desc@)</span></div>',
        '                  <div><span class="seal_level" style="color: #9090ff;margin-right: 20px;">等级：@seal_level@</span>',
        '                  <div class="seal_polar" style="color: #9090ff;">相性：@seal_polar@</span></div>',
        '                  <div class="seal_req_level" style="color: #9090ff;margin-right: 20px;">携带等级：@seal_req_level@级</div>',
        '                  <div class="seal_attrib" style="color: #00FFFF">@seal_attrib@</div>',
        '                  <div class="attrib">@max_convert_times@</div>',
        '                  <div class="attrib">@property_left_time@</div>',
        '                 <div class="limit_exchange_left_time">@limit_exchange_left_time@</div>',
        '                  <div class="niantou_desc" style="width:290px;white-space: normal;">@niantou_desc@</div>',  
        '             </div>',
        '        </div>',
        '    </div>'].join("");
    //装匣模版字符串
    templateString.makeup = ['<div class="templateString-border clearfix" id="templateString_equip">',
        '        <div class="imgleft makeup_imgDiv" style="_margin-left:150px;">',
        '            @important_item@@property_bind_attrib@<img src="http://img.gyyxcdn.cn/qibao/Images/bigdaojuImages/@icon@.jpg" width="120" style="width:120px;"></img>',
        '        </div>',
        '        <div class="textcenter">',
        '            <div class="name">@name@</div>',
        '            <div class="makeupdetail">@makeupdetails@</div>',
        '            <div class="basic_limit">@basic_limit@</div>',
        '        </div>',
        '</div>'].join("");
    //角色详情模版字符串
    templateString.roleview = ['<div class="templateString-noborder" id="templateString_role" style="padding:20px;_padding:0px;">',
          '            <div class="roleleftbg" id="roleleftbg">',
          '                 <ul class="rolelef_tablist" id="rolenav">',
          '                     <li class="roletab"><a href="javascript:;" class=""></a></li>',
          '                     <li class="pettab"><a href="javascript:;" class=""></a></li>',
          '                     <li class="guardtab"><a href="javascript:;" class=""></a></li>',
          '                     <li class="yytab" id="yytab"><a href="javascript:;" class=""></a></li>',
          '                     <li class="equiptab"><a href="javascript:;" class=""></a></li>',
          '                     <li class="dolltab"><a href="javascript:;" class=""></a></li>',
          '                 </ul>',
          '                 <div id="menu_con">',
          /*----------------------------------------角色---start----------------------------------*/
          '                     <div class="tag" style="display:block">',
          '                         <span id="curattrplan1" class="on">&nbsp;</span> ',
          '                         <span id="curattrplan2">&nbsp;</span> ',
          '                         <span class="rd1">',
          '                             <span class="rd1icon" id="rdicon">',
          '                                 @icon@@suit_icon@@show_icon@',
          '                                 <span class="rd1attr" id="rdattr">',
          '                                     <span class="rd1smallimg">@icon@@suit_icon@@show_icon@</span> ',
          '                                     <dl class="rd1attrlist" id="rd1attrlist"> ',
          '                                         <dt class="medicine_jiutxqd">九天玄清丹：@medicine_jiutxqd@</dt> ',
          '                                         <dt class="medicine_yaocqhd">瑶池琼华丹：@medicine_yaocqhd@</dt> ',
          '                                         <dt class="medicine_max_polar_metal">玄金化元丹：@medicine_max_polar_metal@</dt> ',
          '                                         <dt class="medicine_max_polar_wood">苍穹青灵露：@medicine_max_polar_wood@</dt> ',
          '                                         <dt class="medicine_max_polar_water">太阴玄水珠：@medicine_max_polar_water@</dt> ',
          '                                         <dt class="medicine_max_polar_fire">赤焰琉璃丸：@medicine_max_polar_fire@</dt> ',
          '                                         <dt class="medicine_max_polar_earth">昆仑厚土精：@medicine_max_polar_earth@</dt> ',
          '                                         <dt class="medicine_used_sanqingwan">三清丸&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;：@medicine_used_sanqingwan@</dt> ',
          '                                         <dt class="medicine_used_baohua-yuluwan">宝花玉露丸：@medicine_used_baohua-yuluwan@</dt> ',
          '                                         <dt class="medicine_used_jiuzhuan-xianlinglu">九转仙灵露：@medicine_used_jiuzhuan-xianlinglu@</dt> ',
          '                                         <dt class="medicine_polar_point">相性药增加总量：@medicine_polar_point@</dt> ',
          '                                     </dl> ',
          '                                 </span>',
          '                             </span> ',
          '                             <span class="firstrd rd1sp">@name@</span> ',
          '                             <span class="card_point" id="card_point">@card_point@',
          '                                  <span class="sprit" id="sprit">',
          '                                     &nbsp; <b style="font-weight:normal;">精气值：@spirit@</b>',
          '                                  </span>',         
                                        '</span> ',
          '                             <span class="rd1sp" id="month_card_type">@month_card_type@</span> ',
          '                             <span class="rd1sp" id="month_card_time">@month_card_time@</span> ',
          '                             <span class="rd1sp"></span> ',
          '                             <span class="classicpotential">潜能</span>',
          '                             <span class="rd1sp appellations">@title@<span class="sixstar" id="sixstar"></span></span> ',
          '                             <span class="rdhalf rd1sp">@level@</span> ',
          '                             <span class="rdhalf rd1sp reputation" style="margin-left:42px;">@reputation@</span> ',
          '                             <span class="rd1sp mtop">@party_name@</span> ',
          '                             <span class="rd1sp mtop5">@party_contrib@</span> ',
          '                         </span> ',
          '                         <span class="rd2" id="rd2">',
          '                             <span class="rd2zllv">@zhanli_lv@</span> ',
          '                             <span class="generalboundary" id="generalboundary">',
          '                                 <img src="http://img.gyyxcdn.cn/qibao/Images/FlashImages/14662.png">',
          '                                  <span class="generalboundary_details" id="generalboundary_details">',
          '                                     <b style="font-weight:normal;">@fairy_class@</b><br/><b style="font-weight:normal;">@fairy_layer@</b><br/>@fairy_attribs@@fairy_attribs_backup@@fairy_attribs_backup2@@fairy_attribs_backup3@@fairy_daowen_attribs@@niantou_name@@niantou_dur@@niantou_max_dur@',
          '                                  </span>',
          '                             </span>',
          '                             <span class="nogeneralboundary">',
          '                                 <img src="http://img.gyyxcdn.cn/qibao/Images/FlashImages/14663.png">',
          '                             </span>',
          '                             <span class="cw_zhuanhuatimes" id="cw_zhuanhuatimes" style="display:none;">',
          '                                 <img src="http://img.gyyxcdn.cn/qibao/Images/FlashImages/6338.png">',
          '                                  <span class="zhuanhuatimes_details" id="zhuanhuatimes_details">',
          '                                     &nbsp; <b style="font-weight:normal;">@transfer_family@</b><br/><b style="color:red;font-weight:normal;">&nbsp;&nbsp;特别提示：</b>转换门派次数会在次<br/>&nbsp;&nbsp;年1月1日重置为0',
          '                                  </span>',
          '                             </span>',
          '                             <span class="rd2zlscore">@zhanli_score@</span> ',
          '                             <span class="classicpot">@pot@</span>',
          '                             <span class="firstrd rd2sp">@max_life@</span> ',
          '                             <span class="rd2sp" style="margin: 7px 0 4px 51px;width:100px;">@tao@</span> ',
          '                             <span class="firstrds rd2sp">@max_mana@</span> ',
          '                             <span class="rightrd rd2sp">@total_score@</span> ',
          '                             <span class="rd2sp">@phy_power@</span> ',
          '                             <span class="rightrd2 rd2sp">@con@</span> ',
          '                             <span class="rd2sp">@mag_power@</span> ',
          '                             <span class="rightrd2 rd2sp">@wiz@</span> ',
          '                             <span class="rd2sp">@speed@</span> ',
          '                             <span class="rightrd2 rd2sp">@str@</span> ',
          '                             <span class="rd2sp">@def@</span> ',
          '                             <span class="rightrd2 rd2sp">@dex@</span> ',
          '                             <span class="rd2sp rigt">@upgrade_immortal@</span> ',
          '                             <span class="rd2sp rigts">@upgrade_magic@</span> ',
          '                             <span class="rd2sp rd2ab rd2pt" style="width:231px;" data-exp1="@exp@" data-exp4="@exp_ex@" data-exp2="@exp_to_next_level@" data-exp3="@exp_to_next_level_ex@"><span id="perrds" style="width:0%">&nbsp;</span></span> ',
          '                         </span> ',
          '                         <span class="rd2" id="backuprd2">',
          '                             <span class="firstrd rd2sp cur_attrib_plan" style="display:none">@cur_attrib_plan@</span> ',
          '                             <span class="rd2zllv">@zhanli_lv_backup@</span> ',
          '                             <span class="rd2zlscore">@zhanli_score_backup@</span> ',
          '                             <span class="firstrd rd2sp">@max_life_backup@</span> ',
          '                             <span class="rd2sp" style="margin: 7px 0 4px 51px;width:100px;">@tao@</span> ',
          '                             <span class="firstrds rd2sp">@max_mana_backup@</span> ',
          '                             <span class="rightrd rd2sp">@total_score@</span> ',
          '                             <span class="rd2sp">@phy_power_backup@</span> ',
          '                             <span class="rightrd2 rd2sp">@con_backup@</span> ',
          '                             <span class="rd2sp">@mag_power_backup@</span> ',
          '                             <span class="rightrd2 rd2sp">@wiz_backup@</span> ',
          '                             <span class="rd2sp">@speed_backup@</span> ',
          '                             <span class="rightrd2 rd2sp">@str_backup@</span> ',
          '                             <span class="rd2sp">@def_backup@</span> ',
          '                             <span class="rightrd2 rd2sp">@dex_backup@</span> ',
          '                             <span class="rd2sp rigt">@upgrade_immortal_backup@</span> ',
          '                             <span class="rd2sp rigts">@upgrade_magic_backup@</span> ',
          '                             <span class="rd2sp rd2ab rd2pt" style="width:231px;" data-exp1="@exp@" data-exp4="@exp_ex@" data-exp2="@exp_to_next_level@" data-exp3="@exp_to_next_level_ex@"><span id="perrd" style="width:0%">&nbsp;</span></span> ',
          '                         </span> ',
          '                         <span class="rd3" id=rd3>',
          '                             <span class="firstrd rd3sp">@metal@</span> ',
          '                             <span class="rd3sp">@wood@</span> ',
          '                             <span class="rd3sp">@water@</span> ',
          '                             <span class="rd3sp">@fire@</span> ',
          '                             <span class="rd3sp">@earth@</span> ',
          '                             <span class="rd3sp">@polar_point@</span> ',
          '                         </span> ',
          '                         <span class="rd3" id="backuprd3">',
          '                             <span class="firstrd rd3sp">@metal_backup@</span> ',
          '                             <span class="rd3sp">@wood_backup@</span> ',
          '                             <span class="rd3sp">@water_backup@</span> ',
          '                             <span class="rd3sp">@fire_backup@</span> ',
          '                             <span class="rd3sp">@earth_backup@</span> ',
          '                             <span class="rd3sp">@polar_point_backup@</span> ',
          '                         </span> ',
          '                         <span class="rd4">',
          '                             <span class="firstrd rd4sp skill" id="skillbtn"><a href="javascript:;">&nbsp;</a></span> ',
          '                             <span class="rd4sp lwbom" id="lwbombtn"><a href="javascript:;">&nbsp;</a></span> ',
          '                             <span class="rd4sp understand" id="understandbtn"><a href="javascript:;">&nbsp;</a></span> ',
          '                             <span class="rd4sp formation" id="formationbtn" style="display:none;"><a href="javascript:;">&nbsp;</a></span> ',//增加阵型
          '                             <span class="rd4sp lifeRecord" id="lifeRecordbtn"><a href="javascript:;">&nbsp;</a></span> ',//增加浮生录
          '                         </span> ',
          '                         <span style="color: rgb(248, 252, 0); float: left; width: 100%; text-align: left; margin-top: -5px; margin-left: 32px;" class="roledes_tit">'+
          "<p>战力受风灵丸骑乘效果影响（包括未显示的限时骑宠）</p><p style='margin-top:-5px'>属性受变身卡影响，但不受风灵丸骑乘效果影响</p>"+
          '</span> ',
          '                     </div> ',
          /*----------------------------------------角色---end----------------------------------*/
          /*----------------------------------------宠物---start--------------------------------*/
          '                     <div class="tag" style="display:none"> ',
          '                         <div class="cwdiv"> ',
          '                         <div class="cwnav" id="a8"> ',
          '                             <ul id="b8" class="shlef_tablist"><p class="pet_capictity"><span class="petcap_tit">携带数量：</span>@cwcapctity@@pet_capcity@</p>@cwname@</ul>',
          '                             <span class="scrollBarsh" id="c8" style="height: 161px;">',
          '                                 <span class="scrtop">&nbsp;</span>',
          '                                 <span class="tip" id="d8" style="height:20px;"></span>',
          '                                 <span class="scrbottom"></span>',
          '                             </span>',
          '                         </div> ',

          '                             <div id="menu_cw">@cwattr@@cwaptitude@@cwskills@@cwnature@@cwyld@</div>',
          '                         <span class="rd4">',
          '                             <span class="firstrdcw rd4sp skill" id="skillcwbtn"><a href="javascript:;">&nbsp;</a></span> ',
          '                             <span class="rd4sp aptitude" id="aptitudebtn"><a href="javascript:;">&nbsp;</a></span> ',
          '                             <span class="rd4sp talent" id="talentbtn"><a href="javascript:;">&nbsp;</a></span> ',
          '                             <span class="rd4sp stone" id="stonebtn"><a href="javascript:;">&nbsp;</a></span> ',
        '                               <span class="rd4sp nature" id="naturebtn"><a href="javascript:;">&nbsp;</a></span> ',
        '             <span class="rd4sp yld" id="yldbtn" style=" margin-top: 2px;"><a href="javascript:;">&nbsp;</a></span>',
          '                         </span> ',
          '                         </div> ',
          '                     </div> ',
          /*----------------------------------------宠物---end----------------------------------*/
          /*----------------------------------------守护---start--------------------------------*/
          '                     <div class="tag"  style="display:none">',
          '                         <div class="shdiv"> ',
          '                         <div class="shnav" id="a7"> ',
          '                             <ul id="b7" class="shlef_tablist">@shname@</ul>',
          '                             <span class="scrollBarsh" id="c7" style="height: 161px;">',
          '                                 <span class="scrtop">&nbsp;</span>',
          '                                 <span class="tip" id="d7" style="height:20px;"></span>',
          '                                 <span class="scrbottom"></span>',
          '                             </span>',
          '                         </div> ',
          '                             <div id="menu_sh">@shattr@</div>',
          '                         </div> ',
          '                     </div> ',
          /*----------------------------------------守护---end----------------------------------*/
          /*----------------------------------------元婴---start--------------------------------*/
          '                     <div class="tag" style="display:none">',
          '                         <span class="rd1">',
          '                             <span class="rd1icon">',
          '                                 <img class="iconyy" src="http://img.gyyxcdn.cn/qibao/Images/bigItemImages/@iconyy@.png">',
          '                             </span> ',
          '                             <span class="firstrd rd1sp">@nameyy@</span> ',
          '                             <span class="rd1sp"></span> ',
          '                             <span class="rd1sp">@titleyy@</span> ',
          '                             <span class="rdhalf rd1sp">@levelyy@</span> ',
          '                             <span class="rdhalf rd1sp" style="margin-left:40px;">@reputationyy@</span> ',
          '                             <span class="rd1sp">@party_nameyy@</span> ',
          '                             <span class="rd1sp">@party_contribyy@</span> ',
          '                         </span> ',
          '                         <span class="rd2">',
          '                             <span class="firstrd rd2sp">@potyy@</span> ',
          '                             <span class="firstrd rd2sp" style="margin-left: 44px!important;width:100px;">@staminayy@@max_staminayy@</span> ',
          '                             <span class="rd2sp">@taoyy@</span> ',
          '                             <span class="rightrd rd2sp">@total_scoreyy@</span> ',
          '                             <span class="rd2sp">@conyy@</span> ',
          '                             <span class="rightrd2 rd2sp">@upgrade_immortalyy@</span> ',
          '                             <span class="rd2sp">@wizyy@</span> ',
          '                             <span class="rightrd2 rd2sp">@upgrade_magicyy@</span> ',
          '                             <span class="rd2sp">@stryy@</span> ',
          '                             <span class="rightrd2 rd2sp">@upgrade_totalyy@</span> ',
          '                             <span class="rd2sp">@dexyy@</span> ',
          '                             <span class="rightrd2 rd2sp">@attrib_pointyy@</span> ',
          '                             <span class="rd2sp rd2ab rd2pt" style="width:237px;"><span id="perrdyy" style="width:100%">&nbsp;</span></span> ',
          '                             <span class="rd2sp rd2ab" style="width:237px;">@expyy@@exp_to_next_levelyy@</span> ',
          '                         </span> ',
          '                         <span class="rd3">',
          '                             <span class="firstrd rd3sp">@metalyy@</span> ',
          '                             <span class="rd3sp">@woodyy@</span> ',
          '                             <span class="rd3sp">@wateryy@</span> ',
          '                             <span class="rd3sp">@fireyy@</span> ',
          '                             <span class="rd3sp">@earthyy@</span> ',
          '                             <span class="rd3splone">@polar_pointyy@</span> ',
          '                         </span> ',
          '                         <span class="rd4">',
          '                             <span class="yysk rd4sp yyskill" id="yyskillbtn"><a href="javascript:;">&nbsp;</a></span> ',
          '                         </span> ',
          '                     </div> ',
          /*----------------------------------------元婴---end----------------------------------------*/
          /*----------------------------------------装备---start----------------------------------*/
          '                     <div class="tag" style="display:none">',
          '                         <div class="equipbg" id="equipbg">',
          '                             <div id="equip_con">',
          '<img width="16" src="http://img.gyyxcdn.cn/qibao/Images/FlashImages/6332.png" class="js_makeupicon" style="width:23px;height:21px;right: 48px; top: 60px; position: absolute;display:none;">',
          "<img width='16' class='js_treasurepairs' src='http://img.gyyxcdn.cn/qibao/Images/FlashImages/6331.png' style='width:23px;height:21px;right: 48px; top: 123px; position: absolute;z-index:1;'><div class='treasurebg'><span class='treasurebgclose'></span>@treasurenew@</div>",
          "<img width='16' class='js_treasurepairsii' src='http://img.gyyxcdn.cn/qibao/Images/FlashImages/6331.png' style='width:23px;height:21px;right: 48px; top: 123px; position: absolute;z-index:1;'><div class='treasurebgii'><span class='treasurebgclose'></span>@treasurenewii@</div>",
          "<img width='16' class='js_treasurepairsiii' src='http://img.gyyxcdn.cn/qibao/Images/FlashImages/6331.png' style='width:23px;height:21px;right: 48px; top: 123px; position: absolute;z-index:1;'><div class='treasurebgiii'><span class='treasurebgclose'></span>@treasurenewiii@</div>",
          "<img width='16' class='js_treasurepairsiiii' src='http://img.gyyxcdn.cn/qibao/Images/FlashImages/6331.png' style='width:23px;height:21px;right: 48px; top: 123px; position: absolute;z-index:1;'><div class='treasurebgiiii'><span class='treasurebgclose'></span>@treasurenewiiii@</div>",
          "<img width='16' class='js_dress' src='http://img.gyyxcdn.cn/qibao/Images/FlashImages/7732.jpg' style='width:23px;height:21px;right: 110px; top: 60px; position: absolute;z-index:1;'><div class='dressbg'><span class='dressbgclose'></span>@dressnew@</div>",
          "<img width='16' class='js_dressii' src='http://img.gyyxcdn.cn/qibao/Images/FlashImages/7732.jpg' style='width:23px;height:21px;right: 110px; top: 60px; position: absolute;z-index:1;'><div class='dressbgii'><span class='dressbgclose'></span>@dressnewii@</div>",
          "<img width='16' class='js_jade' src='http://img.gyyxcdn.cn/qibao/Images/FlashImages/7734.jpg' style='width:23px;height:21px;left: 76px; top: 60px; position: absolute;z-index:11;'><div class='jadebg'><span class='jadebgclose'></span>@jadenew@</div>",
          "<img width='16' class='js_jadeii' src='http://img.gyyxcdn.cn/qibao/Images/FlashImages/7734.jpg' style='width:23px;height:21px;left: 76px; top: 60px; position: absolute;z-index:11;'><div class='jadebgii'><span class='jadebgclose'></span>@jadenewii@</div>",
          "<img width='16' class='js_jadeiii' src='http://img.gyyxcdn.cn/qibao/Images/FlashImages/7734.jpg' style='width:23px;height:21px;left: 76px; top: 60px; position: absolute;z-index:11;'><div class='jadebgiii'><span class='jadebgclose'></span>@jadenewiii@</div>",
          "<img width='16' class='js_jadeiiii' src='http://img.gyyxcdn.cn/qibao/Images/FlashImages/7734.jpg' style='width:23px;height:21px;left: 76px; top: 60px; position: absolute;z-index:11;'><div class='jadebgiiii'><span class='jadebgclose'></span>@jadenewiiii@</div>",
          "<img width='16' class='js_fairyware' src='http://img.gyyxcdn.cn/qibao/Images/FlashImages/6339.png' style='width:23px;height:21px;right: 48px; top: 185px; position: absolute;z-index:1;'><div class='fairywarebg'><span class='fairywarebgclose'></span>@fairywarenew@</div>",
          "<img width='16' class='js_fairywareii' src='http://img.gyyxcdn.cn/qibao/Images/FlashImages/6339.png' style='width:23px;height:21px;right: 48px; top: 185px; position: absolute;z-index:1;'><div class='fairywarebgii'><span class='fairywarebgclose'></span>@fairywarenewii@</div>",
          /*-------------------------------真身技能---------start---------------------------------*/
          '                                 <div class="tag4" style="display:block;">@eps@</div>',
          /*-------------------------------真身技能----------end----------------------------------*/
          /*-------------------------------真身技能---------start---------------------------------*/
          '                                 <div class="tag4" style="display:block;">@epss@</div>',
          /*-------------------------------真身技能----------end----------------------------------*/
          /*-------------------------------真身技能---------start---------------------------------*/
          '                                 <div class="tag4" style="display:block;">@epsyy@</div>',
          /*-------------------------------真身技能----------end----------------------------------*/
          /*-------------------------------真身技能---------start---------------------------------*/
          '                                 <div class="tag4" style="display:block;">@epssyy@</div>',                             
          /*-------------------------------真身技能----------end----------------------------------*/
          '                             </div>',
          '                             <ul class="equipright_tablist" id="equipnav">',
          '                                 <li class="equipstab"><a href="javascript:;" class="">&nbsp;</a></li>',
          '                                 <li class="equipssparetab"><a href="javascript:;" class="">&nbsp;</a></li>',
          '                                 <li class="equipyytab"><a href="javascript:;" class="">&nbsp;</a></li>',
          '                                 <li class="equipsytab"><a href="javascript:;" class="">&nbsp;</a></li>',
          '                             </ul>',
          '                         </div>',
          '                         <div class="equipmoney" id="equipmoney">@cash@</div>',
          '                         <div class="equipmoneyico"></div>',
          '                         <div class="equipfurnaceico" id="furnace"></div>',
          '                         <div class="equipbag">@bgs@</div>',
          '<div class="makeup_box" style="display:none;">@makeupbox@',
           ' <div class="dataTables_paginate paging_full_numbers" id="DataTables_Table_0_paginate">',
            '<a class="previous paginate_button1" type="last" tabindex="0" id="lastPage1">上一页</a>',
    
            '<span class="js_page"><span class="js_page_on1" id="pageNum1">1</span> / <span id="listCount1">0',
                        
            '</span></span>',
        
            '<a class="next paginate_button1" type="next" tabindex="0" id="nextPage1">下一页</a>',
        
            '</div>',
          '</div>',
          '                     </div> ',
          /*----------------------------------------装备---end------------------------------------*/
          /*----------------------------------------娃娃---start----------------------------------------*/
          '                     <div class="tag"  style="display:none">',
          '                         <div class="wwdiv"> ',
          '                         <div class="wwnav" id="a9"> ',
          '                             <ul id="b9" class="shlef_tablist">@wwname@</ul>',
          '                             <span class="scrollBarsh" id="c9" style="height: 161px;">',
          '                                 <span class="scrtop">&nbsp;</span>',
          '                                 <span class="tip" id="d9" style="height:20px;"></span>',
          '                                 <span class="scrbottom"></span>',
          '                             </span>',
          '                         </div> ',
          '                             <div id="menu_ww">@wwattr@@wwaptitude@@wwskills@@wwcheats@</div>',
          '                         <span class="rd4">',
          '                             <span id="cheatsbtn" class="rd4sp wwcheats"><a href="javascript:;">&nbsp;</a></span>',
          '                             <span id="wwskillbtn" class="rd4sp wwskill"><a href="javascript:;">&nbsp;</a></span>',
          '                             <span id="equipbtn" class="rd4sp wwequip"><a href="javascript:;">&nbsp;</a></span>',
          '                         </span> ',
          '                         </div> ',
          '                         </div> ',
          '                </div>',
          '            </div>',
          /*----------------------------------------娃娃---end----------------------------------------*/
          /*----------------------------------------角色技能---start----------------------------------*/
          '            <div class="skillcenterbg" id="skillcenterbg" style="left: 380px; top: 25px;">',
          '            <span class="skillclose" id="skillclose">&nbsp;</span>',
          '                 <ul class="skillleft_tablist" id="skillnav">',
          '                     <li class="divisiontab"><a href="javascript:;" class=""></a></li>',
          '                     <li class="lifetab"><a href="javascript:;" class=""></a></li>',
          '                     <li class="othertab"><a href="javascript:;" class=""></a></li>',
          '                     <li class="fuxizhenxing" style="display:none;"><a href="javascript:;" class=""></a></li>',//添加伏羲铭文按钮
          '                 </ul>',
          '                 <div id="skill_con">',
          /*------------------角色技能---师门技能--start--------------------*/
          '                     <div class="tag" style="display:block;">',
          '                         <span class="skilltitle">技能名称</span> ',
          '                         <span class="skilltitle sed">技能等级</span> ',
          '                         <span class="scolldiv" id="a1">',
          '                             <ul class="skill_list" id="b1">',
          '                                 @innateskills@',
          '                             </ul>',
          '                             <span class="scrollBar" id="c1"  style="height: 150px;">',
          '                                 <span class="scrtop">&nbsp;</span>',
          '                                 <span class="tip" id="d1" style="height:20px;"></span>',
          '                                 <span class="scrbottom"></span>',
          '                             </span>',
          '                         </span>',
          '                     </div>',
          /*------------------角色技能---师门技能--end--------------------*/
          /*------------------角色技能---生活技能--start--------------------*/
          '                     <div class="tag" style="display:block;">',
          '                         <span class="skilltitle">技能名称</span> ',
          '                         <span class="skilltitle sed">技能等级</span> ',
          '                         <span class="scolldiv" id="a2">',
          '                             <ul class="skill_list" id="b2">',
          '                                 @talentskills@',
          '                             </ul>',
          '                             <span class="scrollBar" id="c2" style="height: 150px;">',
          '                                 <span class="scrtop">&nbsp;</span>',
          '                                 <span class="tip" id="d2" style="height:20px;"></span>',
          '                                 <span class="scrbottom"></span>',
          '                             </span>',
          '                         </span>',
          '                     </div>',
          /*------------------角色技能---生活技能--end--------------------*/
          /*------------------角色技能---其它技能--start------------------*/
          '                     <div class="tag" style="display:none;">',
          '                         <span class="skilltitle">技能名称</span> ',
          '                         <span class="skilltitle sed">技能等级</span> ',
          '                         <span class="scolldiv" id="a3">',
          '                             <ul class="skill_list" id="b3">',
          '                                 @reincarnationskills@',
          '                             </ul>',
          '                             <span class="scrollBar" id="c3" style="height: 150px;">',
          '                                 <span class="scrtop">&nbsp;</span>',
          '                                 <span class="tip" id="d3" style="height:20px;"></span>',
          '                                 <span class="scrbottom"></span>',
          '                             </span>',
          '                         </span>',
          '                         <div class="fuxijianjie">',
          '                             <p class="firText"></p>',
          '                             <p class="secText"></p>',
          '                         </div>',
          '                         <p class="fuxi_exp" style="display:none;"><b style="font-weight:normal">铭文经验：</b><span>@fuxi_exp@</span></p>',
          '                         <p class="fuxi_durability" style="display:none;"><b style="font-weight:normal">耐久度：</b><span>@durability@</span>/<span>@max_durability@</span></p>',
          '                     </div>',
          /*------------------角色技能---其它技能--end------------------*/
          /*------------------角色技能---伏羲阵型--start------------------*/
          '                     <div class="tag" style="display:none;">',
          '                         <span class="skilltitle" style=" width: 118px;">铭文名称</span> ',
          '                         <span class="skilltitle sed" style=" width: 62px;">等级</span> ',
          '                         <span class="skilltitle keyongzx">可用阵型</span> ',
          '                         <span class="scolldiv" id="a4">',
          '                             <ul class="skill_list" id="b4">',
          '                                @fuxizhenxing@',
          '                             </ul>',
          '                             <span class="scrollBar" id="c4" style="height: 150px;">',
          '                                 <span class="scrtop">&nbsp;</span>',
          '                                 <span class="tip" id="d4" style="height:20px;"></span>',
          '                                 <span class="scrbottom"></span>',
          '                             </span>',
          '                         </span>',
          '                         <p class="fuxi_exp"><b style="color:#ecf73b">当前经验：</b>@fuxi_exp@</p>',
          '                     </div>',
          /*------------------角色技能---伏羲阵型--end------------------*/
          '                 </div>',
          '            </div>',
          /*----------------------------------------角色技能---end------------------------------------*/
          /*----------------------------------------元婴技能---start----------------------------------*/
          '            <div class="yyskillcenterbg" id="yyskillcenterbg" style="display:block; visibility:hidden; left: 380px; top: 25px;">',
          '            <span class="skillclose" id="yyskillclose">&nbsp;</span>',
          '                 <ul class="skillleft_tablist" id="yyskillnav">',
          '                     <li class="divisiontab"><a href="javascript:;" class=""></a></li>',
          '                     <li class="lifetab"><a href="javascript:;" class=""></a></li>',
          '                     <li class="othertabyy"><a href="javascript:;" class=""></a></li>',
          '                 </ul>',
          '                 <div id="yyskill_con">',
          /*------------------元婴技能---师门技能--start--------------------*/
          '                     <div class="tag2" style="display:block;">',
          '                         <span class="skilltitle">技能名称</span> ',
          '                         <span class="skilltitle sed">技能等级</span> ',
          '                         <span class="scolldiv" id="a4">',
          '                             <ul class="skill_list" id="b4">',
          '                                 @innateskillsyy@',
          '                             </ul>',
          '                             <span class="scrollBar" id="c4"  style="height: 150px;">',
          '                                 <span class="scrtop">&nbsp;</span>',
          '                                 <span class="tip" id="d4" style="height:20px;"></span>',
          '                                 <span class="scrbottom"></span>',
          '                             </span>',
          '                         </span>',
          '                     </div>',
          /*------------------元婴技能---师门技能--end--------------------*/
          /*------------------元婴技能---生活技能--start--------------------*/
          '                     <div class="tag2" style="display:block;">',
          '                         <span class="skilltitle">技能名称</span> ',
          '                         <span class="skilltitle sed">技能等级</span> ',
          '                         <span class="scolldiv" id="a5">',
          '                             <ul class="skill_list" id="b5">',
          '                                 @talentskillsyy@',
          '                             </ul>',
          '                             <span class="scrollBar" id="c5" style="height: 150px;">',
          '                                 <span class="scrtop">&nbsp;</span>',
          '                                 <span class="tip" id="d5" style="height:20px;"></span>',
          '                                 <span class="scrbottom"></span>',
          '                             </span>',
          '                         </span>',
          '                     </div>',
          /*------------------元婴技能---师门技能--end--------------------*/
          /*------------------元婴技能---其它技能--start------------------*/
          '                     <div class="tag2" style="display:none;">',
          '                         <span class="skilltitle">技能名称</span> ',
          '                         <span class="skilltitle sed">技能等级</span> ',
          '                         <span class="scolldiv" id="a6">',
          '                             <ul class="skill_list" id="b6">',
          '                                 @reincarnationskillsyy@',
          '                             </ul>',
          '                             <span class="scrollBar" id="c6" style="height: 150px;">',
          '                                 <span class="scrtop">&nbsp;</span>',
          '                                 <span class="tip" id="d6" style="height:20px;"></span>',
          '                                 <span class="scrbottom"></span>',
          '                             </span>',
          '                         </span>',
          '                     </div>',
          /*------------------元婴技能---其它技能--end------------------*/
          '                 </div>',
          '            </div>',
          /*-------------------------------------元婴技能--end--------------------------------------*/
          /*-------------------------------------角色悟道--start------------------------------------*/
          '            <div class="wudaoleftbg" id="wudaoleftbg" style=" display: none; top: 132px; left: 53px; ">',
          '                 <span class="wudaoclose" id="wudaoclose">&nbsp;</span>',
          '                 <span class="wudaotitle">悟道</span> ',
          '                 <ul class="wudaoattr_list">',
          '                     <li>悟道境界：<span>@wudao_wudao_stage@</span></li>',
          '                     <li>气血增加：<span>@wudao_life@</span></li>',
          '                     <li>速度增加：<span>@wudao_speed@</span></li>',
          '                     <li>防御增加：<span>@wudao_def@</span></li>',
          '                     <li>伤害增加：<span>@wudao_power@</span></li>',
          '                     <li>已激活附加属性：<span>@wudao_extra_attrib@</span></li>',
          '                     <li>未激活附加属性：<span>@wudao_backup_extra_attrib@</span></li>',
          '                     <li>未激活附加属性：<span>@wudao_backup_extra_attrib2@</span></li>',
          '                     <li>未激活附加属性：<span>@wudao_backup_extra_attrib3@</span></li>',
          '                 </ul>',
          '            </div>',
          /*-------------------------------------角色悟道--end--------------------------------------*/
           /*-------------------------------------角色浮生录--start------------------------------------*/
           '            <div class="lifeRecordbg" id="lifeRecordbg" style=" display: none; top: 132px; left: 53px; ">',
           '                 <span class="lifeRecordclose" id="lifeRecordclose">&nbsp;</span>',
           '                 <span class="lifeRecordtitle">浮生录</span> ',
           '                 <ul class="lifeRecordattr_list">',
        //    '                     <li><em>最大气血：</em><span>@fusheng_max_life@</span></li>',
        //    '                     <li><em>物伤：</em><span>@fusheng_phy_power@</span></li>',
        //    '                     <li><em>法伤：</em><span>@fusheng_mag_power@</span></li>',
        //    '                     <li><em>防御：</em><span>@fusheng_def@</span></li>',
        //    '                     <li><em>速度：</em><span>@fusheng_speed@</span></li>',
        //    '                     <li><em>闪避：</em><span>@fusheng_base_dodge@</span></li>',
        //    '                     <li><em>穿透：</em><span>@fusheng_ignore_absorb@</span><b>%</b></li>',
        //    '                     <li><em>忽视所有抗异常：</em><span>@fusheng_ignore_all_resist_except@</span><b>%</b></li>',
           '                     @fusheng_fushengludiyiban@',

           '                     @fusheng_fushengluwanshan@',    
           '                     <li class="fivestars" id="wuxingka">五星化身</li>',
           '                     @fusheng_fushengwuxingka@',   
           '                     <li class="fivestars" id="wuxingqihun">五星器魂</li>',
           '                     @fusheng_fushengwuxingqihun@',
           '                 </ul>',
           '                 <p class="lifeRecordinstruct">浮生录在奇宝斋上的属性，仅受到角色当前正在使用的加点方案的影响</p>',
           '            </div>',
           /*-------------------------------------角色浮生录--end--------------------------------------*/
            /*-------------------------------------六星称谓--start------------------------------------*/
            '            <div class="appellationsbg" id="appellationsbg" style=" display: none; top: 132px; left: 53px; ">',
            '                 <span class="appellationsclose" id="appellationsclose">&nbsp;</span>',
            '                 <span class="appellationstitle">六星称谓</span> ',
            '                 <ul class="appellationsattr_list">',
           '                     @appellations@',
            '                 </ul>',
            '            </div>',
            /*-------------------------------------六星称谓--end--------------------------------------*/
          /*-------------------------------------角色引灵幡--start----------------------------------*/
          '            <div class="ylfleftbg" id="ylfleftbg" style="display: none; top: 41px; left: 184px;">',
          '                 <span class="ylfclose" id="ylfclose">&nbsp;</span>',
          '                 <span class="ylficonlist" id="ylflist">@yinlingfanskills@@yinlingfangstageshow@</span>',
          '            </div>',
          /*-------------------------------------角色引灵幡--end----------------------------------*/
           /*-------------------------------------角色阵型--start----------------------------------*/
          '            <div class="formation" id="formationleftbg" style="display: none; top: 30px; left: 384px;">',
          '                 <span class="formationclose" id="formationclose">&nbsp;</span>',
          '                 <ul id="js_zxUl"  data-hover="">',
          '                     @zhenxing@',
          '                 </ul>',
          '                 <p class="explain">说明：基础属性由铭文和角色等级决定</p>',
          '                 <div class="zxdiv">',
          '                      <span class="zxSpan" id="js_zxSpanFir">请选择</span>',
          '                      <span class="downArrLef imgA"></span>',
          '                      <ul class="zxUlFir js_zxUlFir">',
          '                         <li>混元一气阵</li>',
          '                         <li>阴阳两仪阵</li>',
          '                         <li>天地三才阵</li>',
          '                         <li>四象玄黄阵</li>',
          '                         <li>五行本源阵</li>',
          '                         <li>乾坤六合阵</li>',
          '                         <li>七曜冲煞阵</li>',
          '                         <li>太极八卦阵</li>',
          '                      </ul>',
          '                 </div>',
          '                 <div class="zxdiv zxdivFir">',
          '                      <span class="zxSpan" id="js_zxSpanSec">请选择</span>',
          '                      <span class="downArrRig imgA"></span>',
          '                      <ul class="zxUlSec js_zxUlSec">',
          '                         <li>混元一气阵</li>',
          '                         <li>阴阳两仪阵</li>',
          '                         <li>天地三才阵</li>',
          '                         <li>四象玄黄阵</li>',
          '                         <li>五行本源阵</li>',
          '                         <li>乾坤六合阵</li>',
          '                         <li>七曜冲煞阵</li>',
          '                         <li>太极八卦阵</li>',
          '                      </ul>',
          '                 </div>',
          '                 <p class="contrastRes"></p>',
          '                 <button class="query" disabled="true"></button>',
          '                 <button class="reset"></button>',
          '            </div>',
          /*-------------------------------------角色阵型--end----------------------------------*/
           /*-------------------------------------丹炉--start------------------------------------*/
           '            <div class="danfurnacebg" id="danfurnacebg" style=" display: none; top: 70px; left: 53px;">',
           '                 <span class="danfurnacebgclose" id="danfurnacebgclose">&nbsp;</span>',
           '                 <span class="danfurnacetitle">配方熟练度</span> ',
           '                 <ul class="danfurnaceattr_list">',
          '                     @danfurnace@',
           '                 </ul>',
           '            </div>',
           '<div class="alternateAttrDesc">当前角色并未使用这套加点方案，因此仅显示角色的点数分配情况</div>',
           /*-------------------------------------丹炉--end--------------------------------------*/
          '    </div>'].join("");
    //背包模版字符串
    templateString.bag = ['<div class="templateString-border clearfix bagbag" id="templateString_equip">',
        '        <div class="imgleft" style="_margin-left:150px;">',
        '             @important_item@<img src="http://img.gyyxcdn.cn/qibao/Images/bigdaojuImages/@icon@.jpg" width="120" style="width:120px;">@property_bind_attrib@',
        '        </div>',
        '        <div class="textcenter">',
        '            <div class="name">@seal_icon@@name@@suit_polar@@rebuild_level@</div>',
        '            <div class="isevolvelevel">@isevolvelevel@</div>',
        '            <div class="holes" style="line-height: 0px;">',
        '                <img src="http://img.gyyxcdn.cn/qibao/Images/FlashImages/@hole1@.png" alt=""/ style="width:16px;">',
        '                <img src="http://img.gyyxcdn.cn/qibao/Images/FlashImages/@hole2@.png" alt=""/ style="width:16px;">',
        '                <img src="http://img.gyyxcdn.cn/qibao/Images/FlashImages/@hole3@.png" alt=""/ style="width:16px;">',
        '            </div>',
        '            <div class="source" style="color: #ff2020">@source@</div>',
        '            <div class="basic_limit">@basic_limit@</div>',
        '            <div class="basic_attrib">@basic_attrib@</div>',
        '            <div class="level clearfix" style="color: #ff2020">@level@</div>',
        '            <div class="yld_capacity_level" style="color:@color@; ">@yld_capacity_level@</div>',
        '            <div class="change_pet_name" style="color:@color@; ">@change_pet_name@</div>',
        '            <div class="default_capacity_level" style="color:@color@; ">@default_capacity_level@</div>',
        '            <div class="qihun_intimacy" style="color:@color@; ">@qihun_intimacy@</div>',
        '            <div class="nimbus clearfix">@nimbus@</div>',
        '            <div class="req_level clearfix">@req_level@</div>',
        '            <div class="upgrade_type  clearfix">@upgrade_type@</div>',
        '            <div class="exp clearfix">@exp_to_next_level@</div>',
        '            <div class="durability clearfix">@max_durability@</div>',
        '            <div class="item_polar clearfix">@item_polar@</div>',
        '            <div class="item_polar_bm clearfix">@item_polar_bm@</div>',
        '            <div class="attrib">@attrib@</div>',
        '            <div class="attach_skill_bm">@attach_skill_bm@</div>',
        '            <div><span class="trigger_rate"">@trigger_rate@</span></div>',
        '            <div><span class="trigger_rate_bm"">@trigger_rate_bm@</span></div>',
        '            <div><span class="extra_skill" style="color:@color@; ">@extra_skill@</span><span class="extra_skill_level" style="color:@color@; ">@extra_skill_level@</span><span class="extra_skill_bm" style="color:@color@; ">&nbsp;&nbsp;@extra_skill_bm@</span><span class="extra_skill_level_bm" style="color:@color@; ">@extra_skill_level_bm@</span></div>',
        '            <div><span class="seal_name" style="color: #9090ff">@seal_name@</span><span class="seal_rank_desc"  style="color: #9090ff">@seal_rank_desc@</span></div>',
        '            <div class="seal_level" style="color: #9090ff;margin-right: 20px;">@seal_level@</div>',
        '            <div class="seal_polar" style="color: #9090ff;margin-right: 20px;">@seal_polar@</div>',
        '            <div class="seal_req_level" style="color: #9090ff;margin-right: 20px;">@seal_req_level@</div>',
        //'            <span class="seal_polar" style="color: #00ff00">@seal_polar@</span></div>',
        '            <div class="seal_attrib" style="color: #00FFFF">@seal_attrib@</div>',
        '            <div class="attrib">@max_convert_times@</div>',
        '            <div class="attrib">@property_left_time@</div>',
        '            <div class="limit_exchange_left_time">@limit_exchange_left_time@</div>',
        '            <div class="suoln_text_desc" style="text-align:left;">@suoln_text_desc@</div>',
        '            <div class="suoln_rank_desc">@suoln_rank_desc@</div>',
        '            <span class="suoln_extra_min">@suoln_extra_min@</span>',
        '            <span class="suoln_extra_max">@suoln_extra_max@</span>',
        '            <div class="incarnation_intimacy">@incarnation_intimacy@</div>',   
        '            <div class="incarnation_intimacy_cumulate">@incarnation_intimacy_cumulate@</div>',  
        '            <div class="niantou_desc" style="width:300px">@niantou_desc@</div>',  
        '        </div>',
        '</div>'].join("");
    //套装模版字符串
    templateString.suit = ['<div class="templateString-border clearfix" id="templateString_suit">',
        '        <div class="textcenter">@icon@</div>',
        '</div>'].join("");
    //套装模带关闭按钮版字符串
    templateString.suits = ['<div class="templateString-border clearfix" id="templateString_suit">',
        '        <div class="textcenter">@icon@</div>',
        '</div>'].join("");
    //首饰套装模版字符串
    templateString.jewelrySuit = ['<div class="templateString-border clearfix" id="templateString_jewelrySuit">',
    '        <div class="textcenter">@icon@</div>',
    '</div>'].join("");
    window.templateString = templateString;
})(window);